#!/usr/bin/env bash
# Extract each contract's spec (SCSpecEntry XDR stream, base64) from the built
# wasm files and embed it in the app, so `funddesk` can build and decode
# transactions offline with `contract.Spec`, without fetching specs from RPC.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WASM_DIR="$ROOT/target/wasm32v1-none/release"
OUT="$ROOT/app/src/chain/specs.ts"
CONTRACTS="ops_account nav_oracle compliance distribution async_vault"
{
  echo "// Generated by scripts/gen-specs.sh from the built wasm files. Do not edit."
  echo "// Base64 stream of SCSpecEntry XDR values for each contract."
  for c in $CONTRACTS; do
    [ -f "$WASM_DIR/$c.wasm" ] || { echo "missing $WASM_DIR/$c.wasm; run stellar contract build first" >&2; exit 1; }
    SPEC=$(stellar contract info interface --wasm "$WASM_DIR/$c.wasm" --output xdr-base64)
    NAME=$(echo "$c" | tr '[:lower:]' '[:upper:]')
    echo "export const ${NAME}_SPEC ="
    echo "  \"$SPEC\";"
  done
} > "$OUT.tmp"
mv "$OUT.tmp" "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
